version: 2

sources:
  - name: dev_dbt_data
    description: "Raw source data tables"
    # Update this to your actual BigQuery dataset
    database: project-gi12345
    schema: dev_dbt_data
    tables:
      - name: course_raw
        description: "Raw course data from seed file"
        columns:
          - name: course_id
            description: "Unique identifier for the course"
          - name: course_name
            description: "Name of the course"
          - name: created_at
            description: "Timestamp when the course was created"
